### ISSUE TITLE
Accessing from non-localhost address fails

### ISSUE THREAD

**Issue by bensonk** [hopsoft/docker-graphite-statsd#16]
If I hit :80 from any IP other than localhost, things fall apart with the following sort of error messages in /var/log/nginx/access.log:

2014/07/30 21:00:06 [crit] 50#0: *197 open() "/var/lib/nginx/fastcgi/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: <client IP redacted>, server: , request: "GET /content/js/ext/ext-all.js HTTP/1.1", upstream: "fastcgi://127.0.0.1:8080", host: "<IP redacted>", referrer: "http://<IP redacted>/composer/?"
2014/07/30 21:00:06 [crit] 50#0: *196 stat() "/opt/graphite/webapp/content/content/js/completer.js" failed (13: Permission denied), client: <client IP redacted>, server: , request: "GET /content/js/completer.js HTTP/1.1", host: "<IP redacted>", referrer: "http://<IP redacted>/composer/?"

**Comment by charliedrage** [comment]
@hopsoft @Gonzih 

Has this issue been addressed / fixed?

**Comment by Gonzih** [comment]
@charliedrage 

I'm just configured my own instance of statsd+graphite without docker :)

**Comment by charliedrage** [comment]
@Gonzih 
Crap. Looks like @hopsoft has updated his Docker imagefile recently on the docker hub anyways though.

**Comment by hopsoft** [comment]
My guess is that port 80 was already being used by a different process on the host. Try having graphite listen on a different port & then forwarding that port on Docker & see what happens. For example:

https://github.com/hopsoft/docker-graphite-statsd/blob/master/conf/nginx/graphite.conf#L2

```
server {
  listen 3000;
```

```
sudo docker run -d \
  --name graphite \
  -p 3000:3000 \
  -p 2003:2003 \
  -p 8125:8125/udp \
  hopsoft/graphite-statsd
```

**Comment by hopsoft** [comment]
Closing for now. Please re-open if this issue persists for you.
