### ISSUE TITLE
Error when mounting volumes

### ISSUE THREAD

**Issue by chenfisher** [hopsoft/docker-graphite-statsd#23]
Hi,

When trying to run the container with mounted volumes as mentioned in the README, I get the following errors:
```
/usr/bin/python: can't open file '/opt/graphite/bin/carbon-aggregator.py': [Errno 2] No such file or directory
/usr/bin/python: can't open file '/opt/graphite/webapp/graphite/manage.py': [Errno 2] No such file or directory
```

I'm trying to run like so:
```
sudo docker run -d \
  --name graphite \
  -v /opt/graphite:/opt/graphite \
  -p 80:80 \
  -p 2003:2003 \
  -p 8125:8125/udp \
  hopsoft/graphite-statsd 
```

When looking into the ```/opt/graphite``` on my host - it's empty

Thanks

**Comment by hopsoft** [comment]
I've been out of town & will have a look at this tonight. Thanks for the report.

**Comment by arthurgeek** [comment]
Anything new? Got the same error.

**Comment by hopsoft** [comment]
If you mount the `/opt/graphite` directory like so:

```
-v /opt/graphite:/opt/graphite
```

The complete graphite configuration needs to live on the host machine at `/opt/graphite`. Please verify that you have a complete [graphite config](https://github.com/hopsoft/docker-graphite-statsd/tree/master/conf/graphite) located under `/opt/graphite` on the host.

**Comment by hopsoft** [comment]
See: https://github.com/hopsoft/docker-graphite-statsd/issues/26#issuecomment-75862129 for tips on how to resolve volume issues.
