### ISSUE TITLE
Unable to bring up the service on the VM created by Vagrant

### ISSUE THREAD

**Issue by adityai** [hopsoft/docker-graphite-statsd#24]
Host: Windows 7
I cloned the repo from github and did a 'vagrant up'. The VM started without errors. 

I did a 'vagrant ssh' and executed the following. 
sudo docker run -d \
  --name graphite \
  -p 80:80 \
  -p 2003:2003 \
  -p 8125:8125/udp \
  hopsoft/graphite-statsd

First time, it threw an error that stated vaguely that the port is already in use. I tried changing the port 80 to 8080, 8081 and a few others but it kept saying that the port is already in use. I could not bring up the service using docker. Am I missing something?

**Comment by adityai** [comment]
I did a 'vagrant destroy' and started the whole process from scratch. It worked fine and graphite is up and running.

**Comment by hopsoft** [comment]
Glad to hear it. I don't have a Windows machine to test with. Thanks for the update.
