### ISSUE TITLE
no need to pip install whisper? or remove the steps of clone and 'python ./setup.py install' for whisper?

### ISSUE THREAD

**Issue by zmstone** [hopsoft/docker-graphite-statsd#25]
# python dependencies
RUN pip install django==1.3\
 python-memcached==1.53\
 django-tagging==0.3.1\
 whisper==0.9.12\         ## this line can be removed since it's installed from source in later steps
 twisted==11.1.0\
 txAMQP==0.6.2

**Comment by hopsoft** [comment]
Nice find. Thanks.

**Comment by hopsoft** [comment]
https://github.com/hopsoft/docker-graphite-statsd/commit/7e26ce4299eec7c1e5477b06f095b25ab2a5dc3e
