### ISSUE TITLE
mount /opt/graphite wont work, or am I doing it wrong ?

### ISSUE THREAD

**Issue by zmstone** [hopsoft/docker-graphite-statsd#26]
As suggested in README: -v /path/to/ebs/graphite:/opt/graphite
if an empty directory on host machine mounted to /opt/graphite in container, graphite won't work.

/usr/bin/python: can't open file '/opt/graphite/bin/carbon-cache.py': [Errno 2] No such file or directory
...

I tried to mount only /opt/graphite/storage, but there are graphite.db and graphite.db-journal already created in the image, which should be preserved.

Finally made it to work by mounting only /opt/graphite/storage/whisper. But I'm not sure if this is the only directory that consumes disk-space.

Also if mount /the/mount/point from the host to /var/log in container, /the/mount/point/nginx and /the/mount/point/graphite should be created on host before running the container.

**Comment by hopsoft** [comment]
You are correct that an empty `/path/to/ebs/graphite` directory on the host will not work as it needs the expected graphite configs etc...

You are also correct that if you mount `/var/log` on the host, you will need to create some subdirectories for things to work. I'll add a note to the readme about this.

**Comment by janpapenbrock** [comment]
What you could do, though, is 

1. run the container without volumes specified
2. docker inspect the host local path of docker created volumes 
3. on the host, copy those paths to a place of your choice
4. run container with volumes at place of your choice

Which involves some not-so-fancy manual copying of paths...

**Comment by janpapenbrock** [comment]
Moreover, this relates to #23, right?

**Comment by hopsoft** [comment]
Yes related to #23. Thanks @janpapenbrock for the excellent tips to help users resolve this & similar issues related to volumes.

**Comment by hopsoft** [comment]
Closing as dup of #23

**Comment by zmstone** [comment]
Thanks for the tip. is it based on a hunch? Or has any one actually made it working this way?
I tried backup a copy of initial db in the image and mount only /opt/graphite/storage, which kind a worked, only there is some issue when start a new cntainer with old volumes mounted again.
I'll look deeper and try to fix the volume issue, pull requests interested?

**Comment by hopsoft** [comment]
Yes pull requests are very welcome.

**Comment by lucas-coelho** [comment]
I have the same problem, any progress about this issue?

**Comment by mclarkson** [comment]
I had to write installation instructions so thought I'd share them:

"What you could do, though, is

1. run the container without volumes specified
2. docker inspect the host local path of docker created volumes
3. on the host, copy those paths to a place of your choice
4. run container with volumes at place of your choice

Which involves some not-so-fancy manual copying of paths..."

Just change BASE var:
```
# All directories will be copied into the BASE directory.
BASE="/opt/servers/graphite"

# Run graphite, copy data, delete graphite.
# You can copy and paste the next lines as a single block
docker run -d --name graphite hopsoft/graphite-statsd
g="/var/tmp/graphite_inspect.$$"
docker inspect graphite >$g
readarray -t SRC < <(sed -n '/Mounts/,/]/ {/Source/ {s/^ *"Source": "\(.*\)",*/\1/p}}' $g)
readarray -t DST < <(sed -n '/Mounts/,/]/ {/Destination/ {s/^ *"Destination": "\(.*\)",*/\1/p}}' $g)
spc=
VOL=
for i in `seq ${#DST[*]}`; do
    [[ -z $BASE ]] && { echo "BASE not set!"; break; }
    mkdir -p "$BASE${DST[i-1]}"
    cp -av "${SRC[i-1]}/"* "$BASE${DST[i-1]}"
    VOL+="${spc}-v \"$BASE${DST[i-1]}:${DST[i-1]}\""
    spc=" "
done
docker stop graphite
docker rm graphite
```
Then start graphite with all mounts, which are in $VOL, for example:
```
# Run graphite properly, with all volume mounts
# 'eval' is required here to parse $VOL correctly (and allow for spaces in paths)
eval docker run -d \
 --name graphite \
 --restart=always \
 -p 80:80 \
 -p 2003-2004:2003-2004 \
 -p 2023-2024:2023-2024 \
 -p 8125:8125/udp \
 -p 8126:8126 \
 $VOL \
 hopsoft/graphite-statsd
```

Thanks for your great work! Cheers! Mark.
