### ISSUE TITLE
Only last 6 hrs shown in Grafana, not able to write graphs with Graphite dashboard.

### ISSUE THREAD

**Issue by drptbl** [hopsoft/docker-graphite-statsd#47]
Hello, I have two issues.

First of all I'm not able to graph anything in my graphite dashboard - with exactly the same date settings and target, data is shown in Grafana properly. I can't understand why. I can't view my graphite data with graphite dashboard, but when I connect the same graphite into Grafana - Grafana shows the data.

Second issue is that my Grafana is showing only data for last 6hrs. After picking bigger range, for example "last 24hrs" - it shows nothing. No data from last 6 hrs, not data from 24 hrs. This is weird.

Any suggestions? Thanks in advance!

**Comment by drptbl** [comment]
You can close this issue, I've fixed that - it was a problem with Graphite configuration.

**Comment by hopsoft** [comment]
Thanks.
