### ISSUE TITLE
Wrong ports description

### ISSUE THREAD

**Issue by vinhlh** [hopsoft/docker-graphite-statsd#62]
https://github.com/hopsoft/docker-graphite-statsd#mapped-ports

2003/2004 are carbon receivers (carbon cache)
2023/2024 are carbon aggregators

**Comment by hopsoft** [comment]
Thanks

**Comment by hopsoft** [comment]
Updated README with new descriptions. https://github.com/hopsoft/docker-graphite-statsd/commit/58d03c62c843725f14f06877cc31d048148c9d81
