### ISSUE TITLE
Reduce Docker image size and layers, re-organize

### ISSUE THREAD

**Issue by janpapenbrock** [hopsoft/docker-graphite-statsd#73]
When I pulled the image to a new machine with disk space constraints, I noticed that it contained a large number of layers and had a pretty large space requirement.

So I applied a number of optimizations to a fork.

You can see the effects per optimization here: https://hub.docker.com/r/hochzehn/docker-graphite-statsd/tags/

Here are the uncompressed numbers (after pull / local build):
```
statsd_8   704.5 MB
statsd_7   704.5 MB
statsd_6   704.5 MB
statsd_5   765.4 MB
statsd_4   768.3 MB
statsd_3   768.3 MB
statsd_2   769 MB
statsd_1   795.5 MB
master     854.2 MB
```

They are built on top of each other, i.e. latest is current `master` branch, `1-no-recommends` builds on top of `master`, `2-single-apt-step` on top of `1-no-recommends`, etc.

You can find the commits here: https://github.com/hochzehn/docker-graphite-statsd/commits/8-cleanup - one commit per optimization. As I realize now, I should have probably labelled them with `1` to `8` as well.

Why did I not create a pull request, you might wonder? I wanted to put the optimizations up for discussion first, as they require a pretty heavy restructuring of `Dockerfile` ([compare](https://github.com/hopsoft/docker-graphite-statsd/compare/master...hochzehn:8-cleanup?w=1)). My largest consideration is splitting installation and configuration of the various components.

Also, some further optimizations could be made, e.g. by dropping `vim` from the image.

So what do you think? The overall effect is pretty cool, I think, and worth the loss in readability. Clustering up e.g. git installations might even make version changes like #57 a little easier.

**Comment by hopsoft** [comment]
Very cool. I'll review in more detail over the holiday. Thanks.

**Comment by janpapenbrock** [comment]
Closing because inactive for > 3 months and not too relevant.
