### ISSUE TITLE
Can't use any other port than 80

### ISSUE THREAD

**Issue by putnap** [hopsoft/docker-graphite-statsd#98]
When setting up this docker image I didn't want to use port 80 as it clashes with IIS on our windows machines, but changing docker run command to other port made it not work at all. 

So my question is, how do I set up this image to work on any other port than 80?

**Comment by masonlr** [comment]
What exact command did you run?

**Comment by putnap** [comment]
docker run -d --name graphite --restart=always -p 127.0.0.1:80:80 -p 127.0.0.1:2003-2004:2003-2004 -p 127.0.0.1:2023-2024:2023-2024 -p 127.0.0.1:8125:8125/udp -p 127.0.0.1:8126:8126 hopsoft/graphite-statsd

**Comment by masonlr** [comment]
Your using `-p 127.0.0.1:80:80` which means 80 on the host side and 80 on the container side. You can change the host side port to anything you want, for example `-p 127.0.0.1:85:80` do bind local 85 to container 80.

**Comment by putnap** [comment]
I'm an illiterate docker user... Thank you!
